### ISSUE TITLE
Sessions not working properly.

### ISSUE THREAD

**Issue by legowtham** [Yunuuuu/mpv-config#1]
What I'm trying to achieve with mpv:

- I want to paste urls to start watching series and can be able to save it as a playlist/session. I want mpv to remember the resume position and the file (episode) position in a playlist. And can be able to resume when mpv is closed and reopened.
- I need to manage different playlists and can get to choose between them (I mostly watch two series parallelly) with uosc osd.

Thankfully, I came across your sessions.lua but it didn't work properly. Problems I face are:

1. I don't want the last played file automatically playing when mpv.exe is opened. I tried setting auto_load=no in sessions.conf, and even disabled=yes in autoload.conf just in case. It still automatically plays the last played session.
2. Multiple sessions are not getting created. If I paste Series-A urls, and close the mpv. Then I reopen it (I had to stop previous session video playing manually) and paste the Series-B urls then I close the player. When reopening, it's not showing the session lists in uosc menu (I've copied your uosc command and pasted in my uosc.conf) , it says Previous sessions > Empty
![Screenshot 2024-11-07 221318](https://github.com/user-attachments/assets/c0c8dcd2-1d8b-411b-81f0-56c5250f4f8a)

Can you please help me to solve this, been trying it for over a week. I love mpv player but it's hard to setup something.

PS: I just use the mpv build from https://github.com/dyphire/mpv-config. I open mpv.exe by clicking and I don't use command line. I've put the sessions.lua in portable_config > scripts and sessions.conf in portable_config > script-opts

Thanks in advance.

**Comment by legowtham** [comment]
@Yunuuuu  Bro can you help me?

**Comment by Yunuuuu** [comment]
Sorry for the delay, I'll take a look tonight.

**Comment by Yunuuuu** [comment]
Can you check your `watch-later` directory? Is there a `mpv-sessions` file?

**Comment by legowtham** [comment]
> Can you check your `watch-later` directory? Is there a `mpv-sessions` file?

Yes i do. Also do I need autoload.lua for sessions to work? Does it depend on it?
![Screenshot 2024-11-22 185830](https://github.com/user-attachments/assets/322e5d33-cc1f-482c-9a4e-565aa503462e)


mpv-sessions contains 1:0
previos-sessions contains 
[playlist]
0
File=*remote url to a movie*

**Comment by Yunuuuu** [comment]
The playlist was not saved properly

**Comment by legowtham** [comment]
> The playlist was not saved properly

You got discord or something :p We can connect if you don;t mind.

**Comment by Yunuuuu** [comment]
How do you close the mpv?

**Comment by Yunuuuu** [comment]
Could you please post the config of sessions?

**Comment by legowtham** [comment]
> How do you close the mpv?

Pressing close button. 

```
# The default config file for sessions
# Available at: https://github.com/Yunuuuu/mpv-config
# add uosc control:
# command:arrow_back_ios:script-message session-attach-prev?Previous history list,command:list_alt:script-message sessions-open-menu?Playlist,command:arrow_forward_ios:script-message session-attach-next?Next history list

# automatically save the prev session
auto_save=yes

# automatically load the previous session if no video for current session
auto_load=yes

# reloads the full playlist from the previous session
# can be individually overwritten when sending script-messages
load_playlist=yes

# file path of the default session file
# save it as a .pls file to be able to open directly (though it will not maintain the playlist positions)
session_file=

# the maximal number of sessions to save
max_sessions=5

# if no, only keep the same session once (session with same playlist will be removed, playlist order matters)
allow_duplicated_session=no

# maintain position in the playlist, do nothing if load_playlist is disabled
maintain_pos=yes

# if previous session is empty, but we do have history sessions, should the empty playlist be restored?
# this occur if you quit manually with stop command. do nothing if auto_load is disabled.
restore_empty=yes

# Check if files still exist, if it don't exist, hide it from the menu
hide_deleted=yes

# Check if files still exist, if it don't exist, remove it from the session
remove_deleted=no

# the default action to switch video via uosc menu, "session-attach" (session_attach or attach) or "session-load" (session_load or load)
switch_action="attach"

# the default execution of mpv, usage for `session-restart` and `session-load` 
mpv_bin=mpv
```

**Comment by legowtham** [comment]
this is menu code in uosc.conf. Do you think this is right? I merged yours and my existing setup using chatgpt

`controls=menu,open-file,<idle>command:history:script-binding recentmenu/open?Recently Played,<idle>command:bookmarks:script-binding simplebookmark/open-list?Bookmarks Menu,<idle>command:file_copy:script-binding smartcopypaste_II/open-list?Clipboard Menu,gap,<!idle>command:analytics:script-binding stats/display-stats-toggle?Statistics,<stream>command:high_quality:script-binding quality_menu/video_formats_toggle?Streaming Quality,<audio,has_image>command:image:script-binding uosc/video#video?Cover,<has_many_edition>editions,<video>video,<has_audio,!audio>audio,<has_sub>subtitles,<has_chapter>chapters,space,<has_chapter>command:skip_previous:add chapter -1?Previous Chapter,<!idle,!image>speed,<has_chapter>command:skip_next:add chapter 1?Next Chapter,space,loop-file,shuffle,loop-playlist,gap,<has_playlist>prev,<has_playlist>playlist,<has_playlist>next,gap,audio-device,gap,fullscreen,gap,command:arrow_back_ios:script-message session-attach-prev?Previous history list,command:list_alt:script-message sessions-open-menu?Playlist,command:arrow_forward_ios:script-message session-attach-next?Next history list`

**Comment by Yunuuuu** [comment]
Did you open a real video?

**Comment by legowtham** [comment]
> Did you open a real video?

Sorry for the delay, I tried with local files. The current playing file is shown in the playlist, but previous played files are not shown when pressing previous and next sessions.
![Screenshot 2024-11-24 154557](https://github.com/user-attachments/assets/672dc1b8-aa8a-4d98-8ea2-2658aa8ce661)

**Comment by Yunuuuu** [comment]
Close it, and reopen mpv program?

**Comment by legowtham** [comment]
> Close it, and reopen mpv program?

Yep, I did it. Playlist is empty. Sessions are empty

**Comment by Yunuuuu** [comment]
It works well in my computer, I don't know why

**Comment by legowtham** [comment]
> It works well in my computer, I don't know why

can you join this anonymous chat. So i can screenshare and we can communicate through chat. link: https://screensharing.metered.live/82mexix_wj

**Comment by Yunuuuu** [comment]
![image](https://github.com/user-attachments/assets/c6c7d6cd-5208-4e76-9307-2f0b84f2fac0)

**Comment by legowtham** [comment]
Wait I'll find different website for screensharing without signing up

**Comment by Yunuuuu** [comment]
I can step into this site <https://screensharing.metered.live/82mexix_wj>

**Comment by legowtham** [comment]
lol chat is not opening

**Comment by legowtham** [comment]
https://screenleap.com/586633595 please join here

**Comment by legowtham** [comment]
https://www.watchparty.me/watch/untidy-cushion-overhear join here

**Comment by Yunuuuu** [comment]
[portable_config.zip](https://github.com/user-attachments/files/17893056/portable_config.zip)

**Comment by Yunuuuu** [comment]
![image](https://github.com/user-attachments/assets/0f328ac6-ae7b-4279-962e-79e25a24b65c)

**Comment by Yunuuuu** [comment]
Here is my `mpv-sessions` file

**Comment by Yunuuuu** [comment]
Hi, the latest version should work

**Comment by Yunuuuu** [comment]
@legowtham

**Comment by Yunuuuu** [comment]
Could you make a test for this?

**Comment by legowtham** [comment]
Will check :))

**Comment by legowtham** [comment]
Its working with urls and my own setup. I can switch through sessions using Next histort list. But the playlists are empty in uosc osd. if you are free, can you join https://www.watchparty.me/watch/untidy-cushion-overhear

**Comment by Yunuuuu** [comment]
should fixed by 70f7378035a2a689625bcd1d921c7f9d4db5101f @legowtham

**Comment by legowtham** [comment]
> should fixed by [70f7378](https://github.com/Yunuuuu/mpv-config/commit/70f7378035a2a689625bcd1d921c7f9d4db5101f) @legowtham

Thank you so much. I can see the title for URLs as well. It's working. I'll test it extensively. Again thanks for fixing :)

**Comment by Yunuuuu** [comment]
I'll close this issue, if there is no issue.

**Comment by legowtham** [comment]
I'll close the issue. I have some feature request. I'll create a new one later. Thank you so much
